version: '3.8'

services:
  ml-service:
    build: .
    container_name: ml-service
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
